version: '3.4'

services:
  sportschedule:
    image: ${DOCKER_REGISTRY}sportschedule
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
        image: "microsoft/mssql-server-windows-express"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"